In [10]:
import pandas as pd
import numpy as np
np.random.seed(50)

data= {
  'name': ['student_' + str(i) for i in range (1,51) ],
  'roll' : range(1,51),
    'age': np.random.randint(18,25,size=50),
  'attendance' : np.random.choice((0,100),size=50),
   'gender': np.random.choice(('Male', 'Female', ' '), size=50),
    'grade' : np.random.choice(('O','A','B','C','F',' '),size=50),
    'score' : [np.random.randint(50, 100, size=3).tolist() for _ in range(50)],
}

df=pd.DataFrame(data)
df.head()

        name  roll  age  attendance  gender grade         score
0  student_1     1   18         100                [63, 71, 78]
1  student_2     2   18           0    Male     F  [71, 91, 64]
2  student_3     3   21         100             A  [63, 97, 85]
3  student_4     4   23         100    Male     F  [56, 62, 92]
4  student_5     5   19           0  Female     A  [96, 50, 95]

In [11]:
df.isnull().sum()

name          0
roll          0
age           0
attendance    0
gender        0
grade         0
score         0
dtype: int64

In [12]:
df.isna()

     name   roll    age  attendance  gender  grade  score
0   False  False  False       False   False  False  False
1   False  False  False       False   False  False  False
2   False  False  False       False   False  False  False
3   False  False  False       False   False  False  False
4   False  False  False       False   False  False  False
5   False  False  False       False   False  False  False
6   False  False  False       False   False  False  False
7   False  False  False       False   False  False  False
8   False  False  False       False   False  False  False
9   False  False  False       False   False  False  False
10  False  False  False       False   False  False  False
11  False  False  False       False   False  False  False
12  False  False  False       False   False  False  False
13  False  False  False       False   False  False  False
14  False  False  False       False   False  False  False
15  False  False  False       False   False  False  False
16  False  False  False       False   False  False  False
17  False  False  False       False   False  False  False
18  False  False  False       False   False  False  False
19  False  False  False       False   False  False  False
20  False  False  False       False   False  False  False
21  False  False  False       False   False  False  False
22  False  False  False       False   False  False  False
23  False  False  False       False   False  False  False
24  False  False  False       False   False  False  False
25  False  False  False       False   False  False  False
26  False  False  False       False   False  False  False
27  False  False  False       False   False  False  False
28  False  False  False       False   False  False  False
29  False  False  False       False   False  False  False
30  False  False  False       False   False  False  False
31  False  False  False       False   False  False  False
32  False  False  False       False   False  False  False
33  False  False  False       False   False  False  False
34  False  False  False       False   False  False  False
35  False  False  False       False   False  False  False
36  False  False  False       False   False  False  False
37  False  False  False       False   False  False  False
38  False  False  False       False   False  False  False
39  False  False  False       False   False  False  False
40  False  False  False       False   False  False  False
41  False  False  False       False   False  False  False
42  False  False  False       False   False  False  False
43  False  False  False       False   False  False  False
44  False  False  False       False   False  False  False
45  False  False  False       False   False  False  False
46  False  False  False       False   False  False  False
47  False  False  False       False   False  False  False
48  False  False  False       False   False  False  False
49  False  False  False       False   False  False  False

In [13]:
df.dtypes

name          object
roll           int64
age            int32
attendance     int64
gender        object
grade         object
score         object
dtype: object

In [17]:
df['gender']=df['gender'].astype(str)

In [20]:
df['gender'].isnull().sum()

np.int64(0)

In [21]:
df.replace(' ', np.nan, inplace=True)

In [22]:
df.isnull()

     name   roll    age  attendance  gender  grade  score
0   False  False  False       False    True   True  False
1   False  False  False       False   False  False  False
2   False  False  False       False    True  False  False
3   False  False  False       False   False  False  False
4   False  False  False       False   False  False  False
5   False  False  False       False   False  False  False
6   False  False  False       False    True  False  False
7   False  False  False       False    True  False  False
8   False  False  False       False   False  False  False
9   False  False  False       False    True  False  False
10  False  False  False       False    True  False  False
11  False  False  False       False    True  False  False
12  False  False  False       False   False  False  False
13  False  False  False       False   False  False  False
14  False  False  False       False   False  False  False
15  False  False  False       False   False  False  False
16  False  False  False       False    True  False  False
17  False  False  False       False   False  False  False
18  False  False  False       False   False   True  False
19  False  False  False       False   False   True  False
20  False  False  False       False   False  False  False
21  False  False  False       False   False  False  False
22  False  False  False       False    True  False  False
23  False  False  False       False    True  False  False
24  False  False  False       False   False  False  False
25  False  False  False       False    True  False  False
26  False  False  False       False   False  False  False
27  False  False  False       False    True  False  False
28  False  False  False       False   False   True  False
29  False  False  False       False   False  False  False
30  False  False  False       False   False   True  False
31  False  False  False       False   False  False  False
32  False  False  False       False   False   True  False
33  False  False  False       False    True  False  False
34  False  False  False       False    True  False  False
35  False  False  False       False   False  False  False
36  False  False  False       False    True  False  False
37  False  False  False       False   False  False  False
38  False  False  False       False   False  False  False
39  False  False  False       False    True  False  False
40  False  False  False       False    True  False  False
41  False  False  False       False    True  False  False
42  False  False  False       False   False  False  False
43  False  False  False       False   False  False  False
44  False  False  False       False   False  False  False
45  False  False  False       False    True  False  False
46  False  False  False       False    True  False  False
47  False  False  False       False    True   True  False
48  False  False  False       False    True   True  False
49  False  False  False       False   False  False  False

In [23]:
df['gender'].fillna("prefer not to say")

0     prefer not to say
1                  Male
2     prefer not to say
3                  Male
4                Female
5                  Male
6     prefer not to say
7     prefer not to say
8                  Male
9     prefer not to say
10    prefer not to say
11    prefer not to say
12                 Male
13                 Male
14                 Male
15               Female
16    prefer not to say
17                 Male
18               Female
19                 Male
20                 Male
21                 Male
22    prefer not to say
23    prefer not to say
24               Female
25    prefer not to say
26                 Male
27    prefer not to say
28               Female
29               Female
30               Female
31                 Male
32               Female
33    prefer not to say
34    prefer not to say
35                 Male
36    prefer not to say
37                 Male
38                 Male
39    prefer not to say
40    prefer not to say
41    prefer not to say
42               Female
43               Female
44               Female
45    prefer not to say
46    prefer not to say
47    prefer not to say
48    prefer not to say
49               Female
Name: gender, dtype: object

In [24]:
df['grade'].isnull()

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30     True
31    False
32     True
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47     True
48     True
49    False
Name: grade, dtype: bool

In [25]:
df['grade'].fillna('Passed')

0     Passed
1          F
2          A
3          F
4          A
5          A
6          C
7          O
8          B
9          O
10         B
11         A
12         O
13         F
14         B
15         F
16         C
17         A
18    Passed
19    Passed
20         C
21         O
22         B
23         O
24         O
25         C
26         F
27         B
28    Passed
29         F
30    Passed
31         O
32    Passed
33         F
34         C
35         C
36         O
37         A
38         C
39         F
40         C
41         F
42         A
43         C
44         F
45         O
46         F
47    Passed
48    Passed
49         A
Name: grade, dtype: object

In [26]:
df.isnull().sum()

name           0
roll           0
age            0
attendance     0
gender        22
grade          8
score          0
dtype: int64

In [27]:
df['avg_Score'] =df['score'].apply(np.mean)

In [28]:
df['avg_Score']

0     70.666667
1     75.333333
2     81.666667
3     70.000000
4     80.333333
5     67.666667
6     91.333333
7     83.333333
8     78.666667
9     77.000000
10    74.000000
11    84.333333
12    86.666667
13    73.000000
14    75.333333
15    77.666667
16    66.333333
17    80.333333
18    71.666667
19    75.333333
20    81.333333
21    86.333333
22    77.000000
23    85.000000
24    82.666667
25    59.666667
26    69.666667
27    62.000000
28    65.333333
29    78.000000
30    84.000000
31    79.666667
32    78.000000
33    63.666667
34    92.000000
35    83.333333
36    57.000000
37    78.000000
38    85.666667
39    78.000000
40    66.333333
41    65.000000
42    93.333333
43    60.333333
44    78.666667
45    73.333333
46    74.666667
47    80.333333
48    79.000000
49    72.000000
Name: avg_Score, dtype: float64

In [31]:
df.isnull().sum()

name           0
roll           0
age            0
attendance     0
gender        22
grade          8
score          0
avg_Score      0
dtype: int64

In [34]:
df['gender']=df['gender'].fillna(df['gender'].mode()[0])

In [35]:
df['gender']

0       Male
1       Male
2       Male
3       Male
4     Female
5       Male
6       Male
7       Male
8       Male
9       Male
10      Male
11      Male
12      Male
13      Male
14      Male
15    Female
16      Male
17      Male
18    Female
19      Male
20      Male
21      Male
22      Male
23      Male
24    Female
25      Male
26      Male
27      Male
28    Female
29    Female
30    Female
31      Male
32    Female
33      Male
34      Male
35      Male
36      Male
37      Male
38      Male
39      Male
40      Male
41      Male
42    Female
43    Female
44    Female
45      Male
46      Male
47      Male
48      Male
49    Female
Name: gender, dtype: object